### ISSUE TITLE
Make 'SLA by design' slogan come true

### ISSUE THREAD

**Issue by EvgenySamoylov** [deckhouse/deckhouse#1069]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

We declare SLA by design which is not 100%. First of all we need to count SLA accurately.

### Proposed Solution

- [x] #1142
- [x] #314
- [x] #1404
- [ ] ~~#1394~~
- [x] Probes
  - [x] #1532
  - [x] Add control-plane/cert-manager probe to check the reaction to CRD change
  - [x] Add basic extensions/dashboard probe  (when in HA mode)
  - [x] Add basic extensions/dex probe  (when in HA mode)
  - [x] Add basic extensions/grafana probe (when in HA mode)
  - [x] Add basic extensions/openvpn probe (no HA mode)
  - [x] Add basic extensions/prometheus-longterm probe (no HA mode)
  - [x] Add kubelet check to maa/metric-sources probe (no HA mode?)
  - [x] Add NodeGroup probe per "cloud" node group
  - [x] #1392
- [x] Telemetry (internal)
  - [x] Sync Upmeter probes with the SLA in the Terms of Service for mk8s
  - [x] Move metrics storage to Okmeter
  - [x] Build dashboards based on Okmeter datasource
  - [x] Display uptime per group per cluster for last 30 days
  - [x] Display the abidance of cluster SLA per component
  - [x] Display SLA violations or close proximity per group
