### ISSUE TITLE
[log-shipper] Module improvements

### ISSUE THREAD

**Issue by EvgenySamoylov** [deckhouse/deckhouse#1070]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Clients, in many cases, can not use the log-shipper module in its current state. We need to collect all the known issues with it and manage them.

### Proposed Solution

- [x] #737 
- [x] #396 
- [x] #318
- [x] #1094
- [x] #1092
- [x] #1149
- [x] #275 
- [x] #269 
- [x] #224
- [x] #1343
- [x] #1433
- [x] #1574
- [ ] #1351 (BLOCKED BY NEW VECTOR RELEASE 0.22)
- [ ] #1093 (BLOCKED BY NEW VECTOR RELEASE 0.22)
- [x] https://github.com/deckhouse/deckhouse/pull/1730
