### ISSUE TITLE
Istio implementation epic 

### ISSUE THREAD

**Issue by EvgenySamoylov** [deckhouse/deckhouse#1408]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

We need to track Istio tasks by milestones (epics) to make its backlog more observable.

### Proposed Solution

- [ ] Improve documentation:
  - [x]  rework readme
  - [ ]  rework usage
- [ ] Update to 1.13:
  - [x] revisions refactoring
  - [ ] update all installations
- [ ] Add some monitoring and alerts
  - [ ] Check if control-plane <-> data-plane interconnection works
  - [ ] Check if sidecar-injector works
  - [x] Check if there are old versions of data-plane in cluster
  - [ ] Federation and multicluster alerts
    - [ ] Check that all the ingressgateways from the list are available
    - [ ] Check that deleted ingressgateways are not discovered (empty list in metadata api)
- [ ]  IngressControllerIstio
- [ ] Chore
  - [x]  `holdApplicationUntilProxyStarts` global parameter
  - [x] istiod antiAffinity
  - [ ] cease upmeter impact to istio
  - [x] custom env for istiod

**Comment by EvgenySamoylov** [comment]
We consider this epic is closed as Istio is currently good to go in the "as is" state. The rest enhancements will be formulated in the separate issues.
