### ISSUE TITLE
[user-authz] EPIC

### ISSUE THREAD

**Issue by EvgenySamoylov** [deckhouse/deckhouse#1419]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

We have several important points to be done around user-authz functionality, which is extremely important to improve the security of the platform.

### Proposed Solution

- [ ] #690
- [ ] Make role-based rights binding model instead of a user-based to decrease the number of objects in the cluster
- [ ] Create multi-tenancy as the resource quotas per namespaces and nodes
