### ISSUE TITLE
Provide instructions on how to safely migrate workloads from the docker to containerd CRI

### ISSUE THREAD

**Issue by EvgenySamoylov** [deckhouse/deckhouse#1420]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

We need to migrate clients' workloads from docker to containerd because of soon docker deprecation in kubernetes.

### Proposed Solution

- [ ] Explain the manual CEPH-CSI migration process
- [x] [Update](https://github.com/deckhouse/deckhouse/issues/2021) ceph-csi driver
- [x] Add the alert with the above instructions for the clusters with the corresponding setup
   - [x] Explain what to do if logs are collected not by log-shipper

**Comment by EvgenySamoylov** [comment]
This is still planned to do.
