### ISSUE TITLE
Make our monitoring and alerts usable with any alert manager

### ISSUE THREAD

**Issue by EvgenySamoylov** [deckhouse/deckhouse#1421]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

We send a lot of group alerts which make sense only in the case you use madison as the alert manager.

### Proposed Solution

- [ ] Make a proxy between cluster prometheus and alert manager to adopt alerts accordingly
- [ ] Do not send groups any more (move this functionality to the madison side)
- [ ] Remove plk_incident_initial_status: "todo" from all the alerts
