### ISSUE TITLE
Provide "out of the box" solution to backup etcd

### ISSUE THREAD

**Issue by EvgenySamoylov** [deckhouse/deckhouse#1441]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

We need to provide the solution to automatically backup the cluster's state somehow "from the box".

### Proposed Solution

This needs further investigation.
- [x] Instruction about how to manually backup and restore ETCD.
    - [x] #2105
    - [x] #1908
- [ ] #2230
- [ ] We need to choose the solution for the separate deckhouse module (Velero is the one of possible options).

**Comment by name212** [comment]
@EvgenySamoylov as you remember we discussed about etcd backups on the last retro and we decided to open issue. I did [it](https://github.com/deckhouse/deckhouse/issues/2230)

I think, we can replace last two tasks in this epic on my issue.

**Comment by EvgenySamoylov** [comment]
For me it looks like #2230 solves 9/10 issues with restoring corrupted state in the cluster if we still have master node in place.
And it definitely could be added as the step in this epic.
But I'm not sure about "replacing the last two tasks", as it doesn't work like a separate backup module and doesn't provide the solution to store backups somewhere outside of the cluster either.
So I prefer "add", but not "replace" for now.

**Comment by nikolayermilov** [comment]
Implemented by:
https://github.com/deckhouse/deckhouse-cli/pull/46
https://github.com/deckhouse/deckhouse/pull/9637
