### ISSUE TITLE
[deckhouse] Updating process

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#149]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

This is an Epic issue to track the progress of improving Deckhouse update process. 

Goals we are aiming to reach:
- Improve flexibility
    - Add update windows
    - Allow update approvals
- Show only relevant changelogs to users

### Proposed Solution

Issues list:
- [x] https://github.com/deckhouse/deckhouse/issues/150
- [x] https://github.com/deckhouse/deckhouse/issues/151
- [x] https://github.com/deckhouse/deckhouse/issues/185
- [x] https://github.com/deckhouse/deckhouse/issues/340
- [x] https://github.com/deckhouse/deckhouse/issues/331
- [x] https://github.com/deckhouse/deckhouse/issues/332
- [x] https://github.com/deckhouse/deckhouse/issues/461
- [x] https://github.com/deckhouse/deckhouse/issues/235
