### ISSUE TITLE
[admission-policy-engine] New module

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#1603]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Goals:
- [x] One of the significant fields covered by Deckhouse is the security of Kubernetes clusters. Policies can forbid users of the platform run pods in system namespaces or under the root user. Admission policies that enforce safety in the cluster are described in [Pod Security Standarts](https://kubernetes.io/docs/concepts/security/pod-security-standards/) document in detail. (#2425)
- [x] To reduce cognitive load for platform users, there should be predefined policy modes out of the box with the ability to extend (#2879).
- [x] #2966
- [x] This module will also help enforce best practices in the clusters with various teams, e.g., always setting resource requests, management labels, etc. (#3131)
- [ ] ~~In Deckhouse, we have an [internal linter](https://github.com/deckhouse/deckhouse/tree/main/testing/matrix/linter). It is utilized only by the CI system and does not apply in runtime. We should consider migrating these lint rules to our policy engine to provide access to these rules for users and to unify the style we use to write policies.~~ (#3345)

### Proposed Solution

The idea is to give users access to the most popular and powerful policy engine, which integrates with Kubernetes perfectly - [Open Policy Engine](https://www.openpolicyagent.org/). 
* There is a tool with predefined policies called [Gatekeeper](https://github.com/open-policy-agent/gatekeeper), which should fully cover our goals.
* To rewrite the linter, it is possible to use OPA in [library mode](https://www.openpolicyagent.org/docs/latest/integration/#integrating-with-the-go-api) and integrate it with Go.
