### ISSUE TITLE
E2E tests improvements

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#1628]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

1. Our e2e tests cover only the primary cases of deploying the cluster and check that Prometheus is deployed successfully. There were ideas like checking upgrade from the previous Deckhouse version to the current or deploying IngressNginxController object to check not only Prometheus and so on.

2. The second problem is stability. Executing the e2e set is not mandatory, so there is always a couple of tests that do not pass. This is annoying, and most engineers are afraid to run tests because they will have to dive into the problem and debug.

### Proposed Solution

* [x] 'Nightly' execute all e2e tests and report errors (#2014)
* [x] Make executing a single e2e test mandatory to accept the PR (#2431)
* [X] Yandex bootstrap takes too long
* [ ] ~~Provide and ability to extend e2e tests and write more checks to cover more functionality (compile a test suit and run it as a post-bootstrap script?) (addressed to @apolovov)~~ (see #2380)
* [x] Add e2e for Deckhouse minor version update (#2283)
* [x] Add a button or a label on GitHub to freeze the e2e cluster for manual debugging (#2534)
* [x] Saved failed cluster for some time after the failed execution for manual debugging (#2534)
* [x] Use separate cloud accounts for e2e tests (to be able to clean them easily) (addressed to @z9r5)
* [x] Have an option to skip tests for a doc change (probably we need other guarantees that doc is deployed successfully) (#2142) 
* [x] #2991
* [x] Run tests on the different OS in the different clouds (#2348)
* [ ] ~~Add some CloudPermanent nodes to clusters (#3082)~~
* [x] Enable automatic integration tests for linstor (#2320)
* [x] Validate images tags (#2512)
