### ISSUE TITLE
Cilium - production ready technology adoption - phase 1 of 3

### ISSUE THREAD

**Issue by zuzzas** [deckhouse/deckhouse#1632]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

We've got stuff to do before Cilium becomes production ready.

### Proposed Solution

- [x]  ~~Enable Cilium to be default on new setups~~
- [x] ~~VXLAN Support: https://github.com/deckhouse/deckhouse/pull/1594~~
- [x] ~~Ensure modules support Cilium's Way of Networking~~
    - [x] ~~Node Local DNS~~
        - [x] ~~LocalRedirectPolicy viability~~
    - [x] ~~istio~~
        ~~Everything except cilium's L7 policies work well.~~
- [x] ~~Enable VPA: https://github.com/deckhouse/deckhouse/pull/1594~~
- [x] ~~Make Hubble turned off by default, as it consumes large amounts of CPU (upstream issue).~~

#### To Do
- [x] https://github.com/deckhouse/deckhouse/issues/4574
- [x] ~~Build kernel checker. #https://github.com/deckhouse/deckhouse/pull/2709~~
  - [x] ~~Check kernel version if cilium module enabled on deckhouse module start and block queue in case if kernel has wrong version.~~
  - [x] ~~Add metric and alerts about wrong kernel version.~~
  - [ ] ~~Add deckhouseReleases requirements and disruptions for cilium minimal kernel version.~~
  - [x] ~~Add init container for cilium agents to prevent run agents on nodes with wrong kernels.~~
- [ ] Provide plan about migration to cilium 1.12
   - [x] #3252
   - [x] #2961 
   - [ ] #2873 
- [x] ~~Check Hubble performance - create an issue in backlog (#3078)~~
- [x] ~~Cilium Service Mesh - create an issue in backlog (#3084)~~
- [ ] Bundling CiliumNetworkPolicies with Deckhouse
   - [ ] Deckhouse host network ciliumClusterWideNetworkPolicies. (#3286)
      - [ ] ~~Possibly using entities instead of enumerating IPs and ports~~. Use of entities leads to unpredictable results.
      - [ ] Consider an option to review policies before applying them to a cluster during Deckhouse upgrades
- [x] #2806
- [ ] Cilium doesn't recognize node IP changing https://github.com/cilium/cilium/issues/17500

#### Backlog

- [ ] keepalived and network-gateway (#1719)
- [x] Possibly migrate existing clusters. Probably, manually. Here is a [success story](https://cilium.io/blog/2020/10/06/skybet-cilium-migration)
- [x] #2886
- [x] ~~#2808~~
- [ ] #2807
- [x] #2900 
- [ ] We need monitoring for the better observability of Cilium
- [ ] #3084
- [ ] #3078
- [x] ~~#3116~~
- [x] #3145
- [x] ~~#3497~~
- [x] https://github.com/cilium/cilium/issues/24417
- [x] https://github.com/cilium/cilium/issues/23930
- [x] https://github.com/cilium/cilium/issues/21955 LoadBalancer/NodePort problem with hostNetwork enppoints (fixed in main)
- [x] DSR with ExternalTrafficPolicy do not work https://github.com/cilium/cilium/issues/10789 fixed in main
- [x] ~~Investigate issues with hostPort (#3035)~~ All works as expected.
- [ ] ingress-nginx (#1718)

Links:

- https://www.datadoghq.com/blog/cilium-metrics-and-architecture/

What we should test in case of new cilium versions:
- nginx inlet `hostWithFailover` - test iptables hack is working.
- create and test iptables port forwarding to kubernetes api - it's temporary solution for external load balancer for kubernetes api (more details in https://flant.slack.com/archives/C78AQG5EY/p1676366607789619) (fixed in 1.13)
- test case when module node-local-dns is enabled, but node-local-dns pods is restarted. Dns redirection should work correctly.
