### ISSUE TITLE
[control-plane-manager] Reduce the number of control plane components patches

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#1643]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

We have patches for kube-apiserver and kube-controller-manager that affect the installation of Deckhouse to clusters where the control-plane-manager module is not enabled, e.g., managed kubernetes services (EKS, GKE, AKS), kind/minikube, clusters we want to adopt.

1. **kube-apiserver** [`ingress-validation.patch`](https://github.com/deckhouse/deckhouse/blob/cc485c3464a108fd350dd2452cdda8817d29265f/modules/040-control-plane-manager/images/kube-apiserver/patches/1.23/ingress_validation.patch) - allows deploying ingress objects to the cluster with both ingress class field and legacy annotation for ingress class set. **This patch completely breaks installations!**
2. **kube-controller-manager** [`pdb-daemonset.patch`](https://github.com/deckhouse/deckhouse/blob/main/modules/040-control-plane-manager/images/kube-controller-manager/patches/1.23/pdb-daemonset.patch) - makes controller manager respect PDB for daemonsets. Without this patch, it is possible to evict all daemonset pods at once, which VPA successfully does.

### Proposed Solution

We need to get rid of the previously mentioned patches.

- [x] Add an afterHelm hook to set annotations with an ingress class to ingress objects. If ingress objects are already in the cluster, set both ingress class and annotation in helm templates.
    - [x] #1671
    - [x] #1676
- [ ] Tune VPA to avoid killing many daemonset pods at once:
    - Set [eviction rate limit](https://github.com/kubernetes/autoscaler/blob/5dbff8d82eb9e8d1a4da01740d3157154be12df9/vertical-pod-autoscaler/pkg/updater/main.go#L52-L56)
       - [x] #1700
    - Avoid using VPA for daemonsets where it is possible
    - Make VPA respect daemonsets replicas fraction. The code for it is lying [here](https://github.com/kubernetes/autoscaler/blob/a5a3052b24102edbafc2fa6681678ff78b8eb579/vertical-pod-autoscaler/pkg/updater/eviction/pods_eviction_restriction.go#L276).
