### ISSUE TITLE
[deckhouse] Release process polishing

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#1941]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

There is a space to improve our current release process. Prime goals of this is deliver more reliable/resilient software more often.

### Proposed Solution

- [ ] Download releases to the cluster earlies so that clients can see the upcoming update
    * Add a cooldown property to the release - the amount of time a release should lay in the cluster before applying it
    * Deckhouse has default update windows for Stable and EarlyAccess release channels - use these channels if no channel is set
- [ ] Provide an ability to send a notification about an upcoming Deckhouse update (via an alert or a webhook).
- [ ] Add a bot to cherry-pick commits to the release branch automatically. Now it is done manually by the release engineer.
- [ ] Stop sending messages in Russian to internal clients
- [ ] Figure out how to track problems on releasing (prepare a doc?)
- [ ] Make it possible to stop and resume a release (as of today, suspended releases become suspended forever)
- [ ] Avoid breaking Deckhouse updates by the failing hook https://github.com/deckhouse/deckhouse/issues/1850
- [ ] Add more info to the flant-pricing module (at least, the updating window information)
