### ISSUE TITLE
Integration tests for modules

### ISSUE THREAD

**Issue by kvaps** [deckhouse/deckhouse#2380]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

We have many unit tests and e2e-tests which are checking that cluster is successfully deployed and running.
But we are not checking internal modules logic. We need a common framework to describe such tests and run them as part of e2e tests

### Proposed Solution

- [ ] Framework for writing and running integration tests on the real cluster
- [ ] Update developers documentation
- [ ] e2e tests should invoke testing suite to test deckhouse modules integrity
- [ ] Testing module and dhctl command to run tests inside the real cluster
- [ ] Rewrite old tests (linstor) to use a new testing framework

**Comment by EvgenySamoylov** [comment]
We're currently working on e2e tests improvement: #1628
