### ISSUE TITLE
Integrate cluster-api instead of MCM to operate over clouds

### ISSUE THREAD

**Issue by EvgenySamoylov** [deckhouse/deckhouse#2477]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

[Machine-controller-manager](https://github.com/gardener/machine-controller-manager) which we use to operate instances in the clouds is slowly developing. We can't bring the new clouds' features to the Deckhouse just because MCM doesn't support them.

### Proposed Solution

Let's consider switching to the [cluster-api](https://github.com/kubernetes-sigs/cluster-api) instead of MCM to operate over clouds as it's a much more dynamically developed project.

We can switch cloud providers to it one by one:
- [ ] AWS (addressed to @zuzzas)
- [ ] GCP
- [ ] Azure
- [ ] OpenStack
- [ ] vSphere

**Comment by EvgenySamoylov** [comment]
It may solve #2463 as well as #2473
