### ISSUE TITLE
Istio - production ready technology adoption

### ISSUE THREAD

**Issue by apolovov** [deckhouse/deckhouse#2675]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

There are some chores.

### Proposed Solution

- [x] Native istio ingress controller https://github.com/deckhouse/deckhouse/issues/140:
  - [x] Figure out how to use `ingress.class: istio`.
  - [x] Design for `IngressIstioController`.
- [x] Get rid of tlsMode https://github.com/deckhouse/deckhouse/issues/2562:
  - [x] Add an alert to 1.37.
  - [x] Wipe from 1.38.
- [x] Automatic data-plane upgrade https://github.com/deckhouse/deckhouse/issues/2144.
- [ ] ~~Ambient mode implementation~~
- [x] #3346
- [x] #3710
- [ ] ~~Monitoring:~~
  - [ ] ~~data-plane <-> control-plane are in sync https://github.com/deckhouse/deckhouse/issues/1883~~
  - [ ] ~~sidecar-injector works https://github.com/deckhouse/deckhouse/issues/1883~~
  - [ ] ~~Remote ingress-gateways are reachable~~
  - [ ] ~~Local ingress-gateways are ready~~
