### ISSUE TITLE
Add support of the Kubernetes 1.25

### ISSUE THREAD

**Issue by EvgenySamoylov** [deckhouse/deckhouse#2788]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Kubernetes 1.26 release cycle [has started](https://github.com/kubernetes/sig-release/tree/master/releases/release-1.26#summary) at Monday 5th September 2022, so it's time for us to support Kubernetes 1.25 in the platform.

### Proposed Solution

According to our Kubernetes support cycle:
- [ ] add 1.25 support
- [ ] deprecate 1.20
- [ ] check firing alerts which block move to the 1.23
- [ ] 1.23 becomes the new version by default
