### ISSUE TITLE
[getting-started] Improvements

### ISSUE THREAD

**Issue by EvgenySamoylov** [deckhouse/deckhouse#2805]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

It's quite important to provide users with the easiest possible way to get the working deckhouse cluster.

### Proposed Solution

- [x] Use nip.io like service. ( #630 #3256)
   - [x] Make a note that some providers block resolving nip.io and similar services. (#3256 )
- [ ] Figure out how to remove master node group taints for the single node installations automatically. (addressed to @z9r5)
- [ ] Provide more information while deploying resources (#2234):
    * Whether the cluster is bootstrapped (and some hints on how to make it bootstrapped)
    * The status of nodes, machines, nodegroups (the most problematic part of this is not to make logs too cumbersome)
- [x] Simplify getting started in general (#3256 )
    * [x] Leave only minimal preset and recommended layout
    * [x] Simplify the configuration used (config.yml, resource.yml)
    * [x] Reduce the number of steps, and condense content.
- [x] kind fixes:
   * Automatic installation only. (#3256)
   * Turn on the monitoringDeckhouse module.  (#3256)
- [ ] Going to Production. Add a production-ready guide/checklist (what users need to do before going to production with Deckhouse) (addressed to @z9r5).
- [x] Collect the most widespread use cases (based on the telegram channel requests) (addressed to @nabokihms)
- [ ] Add post bootstrap script for cloud installations: setpublicDomainTemplate automatically, wait fo readiness of certificates.
