### ISSUE TITLE
Yandex CSI Epic

### ISSUE THREAD

**Issue by zuzzas** [deckhouse/deckhouse#2956]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Yandex.Cloud has a couple of outstanding bugs. It's repository should also be updated with proper CI and testing.

### Proposed Solution

- [x] Deleted PVs may still be present in cloud Disks
- [x] Slow detach (much slower than other cloud providers)
- [x] Online resize is not supported. Consider improving offline-resize to ease the burden on cluster admins.

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.

**Comment by pkonovalov** [comment]
Online resize is now supported in Yandex Compute Cloud
https://github.com/yandex-cloud/docs/commit/42829b1fc0462033763ddee88004938717c0433f
