### ISSUE TITLE
[deckhouse-config] more improvements

### ISSUE THREAD

**Issue by diafour** [deckhouse/deckhouse#3097]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Some improvements after merging #1729.

### Code

- [ ] 1. res.IsConverted seems redundant. Also, looping over allConfigs can be [deduplicated](https://github.com/deckhouse/deckhouse/pull/1729#discussion_r1025156172).
- [ ] 2. Hard-coded increment for versions. This can reduce arguments for conversion functions.
- [ ] 3. Use slice instead of `conversions map[int]*Conversion` and call Sort in the Add method. See this [comment](https://github.com/deckhouse/deckhouse/pull/1729#discussion_r1025091771).

### Corner cases

- [ ] 1. There is a chance that conversion functions may fail to convert a configuration before AddonOperator starts. There is no way to update image to the hotfix version in this situation.
- 2. Possible soultions:
  2.1. Use separate Deployment for deckhouse updates.
  2.2. Passthrough error to the deckhouse-config module.
- [ ] 3. Drop support for obsolete versions. There should be a support in Disruptive Update mechanism to prevent update when there are ModuleConfig resources with dropped versions.
- [ ] 4. Empty spec.settings (`spec: {"version": 2, "settings": {} }`). There are some modules with required fields on the top level. It is a good idea to show error if spec.settings are empty.

### Helpers
- [ ] 1. Create README for developers on conversion concepts and testing. It may be wiki page.
- [ ] 2. README on how to delete all created resources to start migration again. #2977
- [ ] 3. Create snippet to help migrate configurations #2980

### Features

- [ ] 1. Mutating webhook and an option to enable auto-migration. It may be useful for "one-time" or developer clusters to auto migrate ModuleConfig resources.
- [ ] 2. Write latest settings into the "latest-version-settings-applied" annotation (as with the "last-applied-configuration" annotation).
- [ ] 3. Auto-migration "always on". Enable mutating webhook for all clusters. Discover if 3-way-merge patch in Helm will merge spec.settings. "Always on" will not be an option in this case.
- [ ] 4. "Invalid config" metric and alert. Invalid configuration is a rare situation now. Alert can be dropped. But this metric can be useful if configuration is changed when webhook is disabled.
- [ ] 5. More data for conversion functions. There may be conversions that require resources from the cluster, e.g. annotations on Secrets. Global values and module values as requirements is the next level.
- [ ] 6. Use ModuleConfig for installation #2975 

### Proposed Solution

.
