### ISSUE TITLE
[delivery] New module

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#313]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Consider adding a new module to be able to pull cluster configurations right after the cluster creation.

### Proposed Solution

The proposed solution is to integrate ArgoCD into the Deckhouse ecosystem. It matches perfectly with existed modules like Dex and CertManager.

### TODO 

MVP checklist is tracked in #707 

#### Non-MVP checklist

- [ ] #3416
- [ ] #3417
- [ ] Argo CD RBAC: ensure user can control user access rights
- [ ] Collect metrics
- [ ] Images 
  - [ ] kube-rbac-proxy
- [ ] Demo application or complete tutorial with werf bundle?
- [ ] Support custom public keys in argocd-ssh-known-hosts-cm-configmap.yaml
- [ ] Re-generate admin password in the Argo-way (?)
