### ISSUE TITLE
[site] Improve site search

### ISSUE THREAD

**Issue by z9r5** [deckhouse/deckhouse#326]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

There are some issues with a search on the site to solve:

- [ ] ones cannot search by part of a word (e.g - RemoteWrite instead of PrometheusRemoteWrite,)
- [ ] search rules are not shown
- [ ] search by name of  parameter from an OpenAPI specification (#1773 )
- [ ] better search in snippets ([query](https://deckhouse.io/en/documentation/v1/search.html?query=kind%3A+User) returns nothing)

Partly improved in #3591
What next:
- Group search result by modules. Like in google
  ![image](https://user-images.githubusercontent.com/6360800/214809900-94a6d35f-74ef-4536-a13c-37b83ab6a205.png)
- Count dots in content as a separator for words. Ex. searching for certSANs should display document with the `controlPlaneManager.apiserver.certSANs` frase inside.
