### ISSUE TITLE
External modules epic

### ISSUE THREAD

**Issue by yalosev** [deckhouse/deckhouse#3970]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

External modules follow-up

### Proposed Solution

```[tasklist]
### Phase 1 (active development):
- [x] Update windows and mode
- [ ] https://github.com/deckhouse/deckhouse/issues/3971
```

```[tasklist]
### Phase 2 (spacewalk):
- [x] External module documentation
- [ ] Enable/disable one module without Deckhouse restart
- [ ] Reload one module without Deckhouse restart
- [ ] Webhooks (validation, mutation, conversion)
- [ ] External module fs restrictions (grant access only for /tmp directory)
- [ ] Security stuff
- [ ] Dedicated queue for external module
```

```[tasklist]
### Phase 3 (ready-to-eat):
- [ ] some kind of external modules store
- [ ] Values encapsulation (avoid the need of the values form like `.Values.$moduleName.internal.something`)
- [x] External module telemetry
- [ ] External module tests
```

```[tasklist]
### Phase 4 (the Migration period):
- [ ] External module dependencies
  - [ ] from other modules
  - [ ] from system components (k8s version, node kernel version, etc)
```

```[tasklist]
### Phase 5 (it's a final countdown):
- [ ] Smart cache (no hostPath)
- [ ] Reverse dependencies   (deckhouse can't be updated because of the old module)
- [ ] Helm_lib dependencies
```

**Comment by gyrter** [comment]
Hello, @yalosev.

On installation in managed cluster I got error
```
Events:
  Type     Reason       Age                  From               Message
  ----     ------       ----                 ----               -------
  Normal   Scheduled    2m41s                default-scheduler  Successfully assigned d8-system/deckhouse-config-webhook-7dbb594bb6-pxs2m to dev-node-dan9y
  Warning  FailedMount  97s (x8 over 2m41s)  kubelet            MountVolume.SetUp failed for volume "external-modules" : hostPath type check failed: /var/lib/deckhouse/external-modules is not a directory
  Warning  FailedMount  38s                  kubelet            Unable to attach or mount volumes: unmounted volumes=[external-modules], unattached volumes=[webhook-certs external-modules kube-api-access-q7rp9]: timed out waiting for the condition
```
