### ISSUE TITLE
[linstor] epic

### ISSUE THREAD

**Issue by apolovov** [deckhouse/deckhouse#4026]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

It is epic.

### Proposed Solution

**Backlog:**
- [ ] [linstor] encrypted storageclass (create a doc or automate it)
- [ ]  piraeus v2.0
- [ ] auto-diskful
