### ISSUE TITLE
[META] Add explicit defaults to ModueConfigs and Custom Resources

### ISSUE THREAD

**Issue by shvgn** [deckhouse/deckhouse#4050]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

In Deckhouse, there are many places where configuration applies implicitly. When user c creates and object, like ModuleConfig, or VsphereInstanceClass, they don't see the exact configuration applied to the corresponding features.

For now, we have at least two different cases for configuration defaults:

#### OpenAPI schema defaults

They are applied during schema validation and transmitted to internal module (global) values and then rendered in templates or written to internal values to effect on hooks behaviour. 

For example, in ModuleConfig/deckhouse, on can completely omit 'update' section, while `update.mode = 'Auto'` will still be implied.

#### Calculated defaults

They are deduced from multiple places, e.g. from terraform data, or NodeGroup/master. 

For example, in VsphereInstanceClass, one can omit machine template, so the object will be created without this field. The actual machine template from 'master' node group will be used implicitly

### Proposed Solution

There are stages to make defaults explicit

#### Schema defaults 

The defaults become initial values, so they are set explicitly by mutating webhook is not set by user.

- [ ] Stage 1. In ModuleConfigs, render all config-values defaults to `spec.settings`, also revise x-defaults to make them schema defaults where possible. 
- [ ] Stage 2. In ModuleConfigs, render the tree of default values in `status.defaultSettings`

#### Computed defaults

- [ ] Stage 3. In Custom Resources, render all computed defaults to `status.computedDefaults`

### Additional Information

There will be cases when we would not want to keep fixed values in ModueConfigs or CRs, e.g. the default version of Ingress Controller. In this case, we have two options:

- support 'Automatic' option, so the value will become _computed default_
- or support migrations or disruptive update requirements for this kind of configuration
