### ISSUE TITLE
[module] Documentation

### ISSUE THREAD

**Issue by raabdullaev-fl** [deckhouse/deckhouse#6145]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

-

### Proposed Solution

```[tasklist]
### Documentation builder (Issue #6274)
- [x] Create layout for modules documentation (#6381)
- [x] Create http server with the next API handlers (_/loadDocArchive_, _/build_) (#6335)
- [ ] On service startup create ConfigMap `docs-sync`
- [x] Add service for deckhouse.io docs with separate ingress path
```

```[tasklist]
### Documentation loader
- [ ] https://github.com/deckhouse/deckhouse/issues/6275
- [ ] Create a hook inside 005-external-module-manager to send module docs for builder (in-cluster docs)
``` 

### Additional Information
- [ ] Render OpenAPI spec (#6606)

![Image](https://github.com/deckhouse/deckhouse/assets/4477098/d025128d-5faf-4cd5-93f4-a128ea2b9402)
