### ISSUE TITLE
CI improvements

### ISSUE THREAD

**Issue by EvgenySamoylov** [deckhouse/deckhouse#788]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

We need to address some issues in the current CI process to improve DX.

### Proposed Solution

Issues list:

- [x] #777
- [x] #735
- [x] #706 
- [x] #795
- [x] #796
- [x] https://github.com/deckhouse/deckhouse/issues/849
- [x] Build FE and build modules in parallel (addressed to @apolovov to create the issue)
- [x] How to test CI for the features that are not in the main branch yet (addressed to @nabokihms to create the issue)
- [x] #812
- [ ] #899
- [ ] #895
- [x] #941
- [x] #957

**Comment by EvgenySamoylov** [comment]
We consider this epic is closed as the CI process is good enough in the "as is" state. The rest enhancements will be implemented in the separate issues.
