### ISSUE TITLE
Make deckhouse releases smooth

### ISSUE THREAD

**Issue by EvgenySamoylov** [deckhouse/deckhouse#789]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

We need to release the new versions of Deckhouse so that cluster users and applications are not affected anyhow.

### Proposed Solution

Issues list:

- [ ] Fix the lack of monitoring for all the needed components (issue is not addressed yet).
- [ ] Make the zero traffic loss while updating ingresses (addressed to @nabokihms to investigate).
- [x] [#294](https://github.com/flant/addon-operator/pull/294)
