### ISSUE TITLE
Go hooks improvements

### ISSUE THREAD

**Issue by EvgenySamoylov** [deckhouse/deckhouse#804]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

We plan to eliminate bash from the hooks' code because of difficulties with tests coverage and maintenance.

### Proposed Solution

Issues list:

- [x] #1799
- [x] cloud-provider-openstack (addressed to @zuzzas)
- [x] #572
- [x] #517
- [x] #813
- [x] fix the rest global hooks (not addressed yet)
- [ ] ~~If we need to fix the enable scripts? (not addressed yet)~~
- [ ] ~~to cover the rest bash code with tests (not addressed yet)~~
- [x] 300-prometheus (addressed to @yalosev)
- [x] 500-dashboard (#2133)
- [x] 340-monitoring-kubernetes-control-plane (#2905)
- [x] 450-network-gateway (addressed to @yalosev))
- [x] 380-metallb - starting from the version 0.13 it's possible to configure metallb through custom resources. (#2595)
