### ISSUE TITLE
[linstor] Workflow

### ISSUE THREAD

**Issue by kvaps** [deckhouse/deckhouse#902]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Before we implement KubeVirt https://github.com/deckhouse/deckhouse/issues/602 we need to have a storage.
This storage should be reliable and fast on write to meet the virtualization needs and run fully in Kubernetes environment.

Many Deckhouse users on bare-metal are also require on such solution.

### Proposed Solution

Issues list:
- [X] **[upstream]** https://github.com/piraeusdatastore/piraeus-operator/pull/260
- [X] **[upstream]** https://github.com/piraeusdatastore/piraeus-operator/pull/261
- [X] **[upstream]** https://github.com/piraeusdatastore/piraeus-operator/pull/262
- [X] **[upstream]** https://github.com/piraeusdatastore/piraeus-operator/pull/263
- [X] **[upstream]** https://github.com/piraeusdatastore/piraeus-operator/pull/266
- [X] **[upstream]** https://github.com/piraeusdatastore/piraeus-operator/pull/269
- [x] **[upstream]** https://github.com/piraeusdatastore/piraeus-operator/pull/268
- [x] https://github.com/deckhouse/deckhouse/issues/908
- [x] https://github.com/deckhouse/deckhouse/issues/830
- [x] https://github.com/deckhouse/deckhouse/issues/603
- [x] https://github.com/deckhouse/deckhouse/issues/929
- [x] https://github.com/deckhouse/deckhouse/issues/904
- [x] https://github.com/deckhouse/deckhouse/issues/903
- [x] https://github.com/deckhouse/deckhouse/issues/905
- [x] https://github.com/deckhouse/deckhouse/issues/906
- [x] https://github.com/deckhouse/deckhouse/issues/907
- [x] https://github.com/deckhouse/deckhouse/pull/1053
- [x] https://github.com/deckhouse/deckhouse/pull/1147
- [x] https://github.com/deckhouse/deckhouse/issues/1067
- [x] https://github.com/deckhouse/deckhouse/issues/914
- [x] https://github.com/deckhouse/deckhouse/issues/909
